# Generated by Django 4.2.7 on 2023-11-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comidas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comidas",
            old_name="title",
            new_name="bairro",
        ),
        migrations.RenameField(
            model_name="comidas",
            old_name="created",
            new_name="endereco",
        ),
        migrations.RenameField(
            model_name="comidas",
            old_name="deadline",
            new_name="horario",
        ),
        migrations.RemoveField(
            model_name="comidas",
            name="finished",
        ),
        migrations.AddField(
            model_name="comidas",
            name="distancia",
            field=models.IntegerField(null=True),
        ),
    ]
