# Generated by Django 4.2.7 on 2023-11-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comidas", "0002_rename_title_comidas_bairro_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comidas",
            name="id",
        ),
        migrations.AddField(
            model_name="comidas",
            name="inaugurado",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="comidas",
            name="nome",
            field=models.CharField(
                default="Não Encontrado",
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="comidas",
            name="endereco",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="comidas",
            name="horario",
            field=models.TimeField(),
        ),
    ]
