# Generated by Django 4.2.7 on 2023-11-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comidas", "0003_remove_comidas_id_comidas_inaugurado_comidas_nome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="bares",
            fields=[
                (
                    "nome",
                    models.CharField(
                        default="Não Encontrado",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bairro", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=100)),
                ("horario", models.TimeField()),
                ("distancia", models.IntegerField(null=True)),
                ("inaugurado", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="cinemas",
            fields=[
                (
                    "nome",
                    models.CharField(
                        default="Não Encontrado",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bairro", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=100)),
                ("horario", models.TimeField()),
                ("distancia", models.IntegerField(null=True)),
                ("site", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variaveis", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="lazer",
            fields=[
                (
                    "nome",
                    models.CharField(
                        default="Não Encontrado",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bairro", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=100)),
                ("horario", models.TimeField()),
                ("distancia", models.IntegerField(null=True)),
                ("site", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="praias",
            fields=[
                (
                    "nome",
                    models.CharField(
                        default="Não Encontrado",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bairro", models.CharField(max_length=20)),
                ("referencial", models.CharField(max_length=50)),
                ("distancia", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="turismo",
            fields=[
                (
                    "nome",
                    models.CharField(
                        default="Não Encontrado",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bairro", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=100)),
                ("horario", models.TimeField()),
                ("distancia", models.IntegerField(null=True)),
                ("site", models.URLField()),
            ],
        ),
    ]
